import React from 'react';
import type { Module, SidebarItem } from './types';

// Placeholder Icons
const DashboardIcon: React.FC<{ className?: string }> = ({ className }) => <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2V6zM14 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V6zM4 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2v-2zM14 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z" /></svg>;
const GeoCommandIcon: React.FC<{ className?: string }> = ({ className }) => <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2h1a2 2 0 002-2v-1a2 2 0 012-2h1.945M7.707 4.293l.707-.707a2 2 0 012.828 0l.707.707M15.586 21a2 2 0 01-2.828 0l-.707-.707M7.707 21l.707-.707a2 2 0 00-2.828 0l-.707.707M15.586 4.293l.707.707a2 2 0 002.828 0l.707-.707" /></svg>;
const AiAnalyzerIcon: React.FC<{ className?: string }> = ({ className }) => <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>;
const OptimizationIcon: React.FC<{ className?: string }> = ({ className }) => <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6V4m0 16v-2m8-8h2m-18 0h2m14.485-6.485l1.414-1.414M5.101 19.5l1.414-1.414M19.5 19.5l-1.414-1.414M4.515 5.101L5.929 6.515M12 18a6 6 0 100-12 6 6 0 000 12z" /></svg>;
const AuditorIcon: React.FC<{ className?: string }> = ({ className }) => <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" /></svg>;
const ReportsIcon: React.FC<{ className?: string }> = ({ className }) => <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V7a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>;
const SettingsIcon: React.FC<{ className?: string }> = ({ className }) => <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066 2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" /></svg>;
const CIIcon: React.FC<{ className?: string }> = ({ className }) => <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /></svg>;
const ChatGptIcon: React.FC<{ className?: string }> = ({ className }) => <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path d="M7 8h10M7 12h4m1 8l-4-4H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-3l-4 4z" /></svg>;
const PerplexityIcon: React.FC<{ className?: string }> = ({ className }) => <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>;
const GeminiIcon: React.FC<{ className?: string }> = ({ className }) => <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z" /></svg>;
const ClaudeIcon: React.FC<{ className?: string }> = ({ className }) => <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" /></svg>;
const DeepSeekIcon: React.FC<{ className?: string }> = ({ className }) => <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" /></svg>;
const CopilotIcon: React.FC<{ className?: string }> = ({ className }) => <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" /></svg>;
const SourceIntelIcon: React.FC<{ className?: string }> = ({ className }) => <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0zM10 7L3 14" /></svg>;
const BrandPowerIcon: React.FC<{ className?: string }> = ({ className }) => <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path d="M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l-3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3" /></svg>;
const DominationIcon: React.FC<{ className?: string }> = ({ className }) => <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" /></svg>;
const ForecasterIcon: React.FC<{ className?: string }> = ({ className }) => <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6" /></svg>;
const TopicConquestIcon: React.FC<{ className?: string }> = ({ className }) => <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path d="M15 15l-2 5L9 9l11 4-5 2zm0 0l5 5M7.188 2.239l.777 2.897M5.136 7.965l-2.898-.777M13.95 4.05l-2.122 2.122m-5.657 5.656l-2.12 2.122" /></svg>;
const GlobalExpansionIcon: React.FC<{ className?: string }> = ({ className }) => <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path d="M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2h1a2 2 0 002-2v-1a2 2 0 012-2h1.945M12 12a10 10 0 11-5.94-9.14" /></svg>;
const ApiHubIcon: React.FC<{ className?: string }> = ({ className }) => <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>;
const TemplatesIcon: React.FC<{ className?: string }> = ({ className }) => <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path d="M4 6h16M4 12h16M4 18h7" /></svg>;
const PerformanceIcon: React.FC<{ className?: string }> = ({ className }) => <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>;
const SyndicationIcon: React.FC<{ className?: string }> = ({ className }) => <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path d="M8.684 13.342C8.886 12.938 9 12.482 9 12s-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.368a3 3 0 105.367 2.684 3 3 0 00-5.367-2.684z" /></svg>;
const VideoIcon: React.FC<{ className?: string }> = ({ className }) => <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path d="M15 10l4.553-2.276A1 1 0 0121 8.618v6.764a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z" /></svg>;
const UniversalHubIcon: React.FC<{ className?: string }> = ({ className }) => <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z" /></svg>;
const ProductSchemaIcon: React.FC<{ className?: string }> = ({ className }) => <svg className={className} xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" d="M9.568 3H5.25A2.25 2.25 0 003 5.25v4.318c0 .597.237 1.17.659 1.591l9.581 9.581c.699.699 1.78.872 2.607.33a18.095 18.095 0 005.223-5.223c.542-.827.369-1.908-.33-2.607L11.16 3.66A2.25 2.25 0 009.568 3z" /><path strokeLinecap="round" strokeLinejoin="round" d="M6 6h.008v.008H6V6z" /></svg>;
const ProductDescriptionIcon: React.FC<{ className?: string }> = ({ className }) => <svg className={className} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M497.9 142.1L405.8 50.02C394.3 38.53 376.6 32 359 32s-35.3 6.531-46.82 18.02L20.15 310C-1.01 331.2-6.531 359.8 4.219 385.8l61.59 106.8c10.75 18.66 29.81 30.25 50.84 31.95c.2969 .0234 .5938 .0469 .8906 .0469c17.66 0 35.25-6.75 48.02-19.52l292.1-292.1C520.6 195.9 520.6 160.8 497.9 142.1zM52.89 421.1l-43.11-74.67l211.2-211.2l74.67 43.11L52.89 421.1zM345.5 124.5l-74.67-43.11l46.82-46.82c5.219-5.219 13.67-5.219 18.89 0l55.78 55.78c5.219 5.219 5.219 13.67 0 18.89L345.5 124.5z"/></svg>;


export const SIDEBAR_ITEMS: SidebarItem[] = [
  { id: 'dashboard', label: 'Dashboard', icon: DashboardIcon },
  { id: 'geo_command_center', label: 'GEO Command Center', icon: GeoCommandIcon },
  { id: 'analytics', label: 'AI Visibility Analyzer', icon: AiAnalyzerIcon },
  { id: 'optimization', label: 'Optimization Engine', icon: OptimizationIcon },
  { id: 'technical_geo_auditor', label: 'Technical Geo Auditor', icon: AuditorIcon },
  { id: 'reports', label: 'Reporting Hub', icon: ReportsIcon },
  { id: 'settings', label: 'Settings', icon: SettingsIcon },
];

export const TOP_NAV_ITEMS = [
    { id: 'dashboard', label: 'Dashboard' },
    { id: 'analytics', label: 'AI Visibility Analyzer' },
    { id: 'optimization', label: 'Optimization Engine' },
    { id: 'competitive_intelligence', label: 'Competitive Intelligence' },
    { id: 'reports', label: 'Reporting Hub' },
    { id: 'settings', label: 'Settings' },
];

export const MODULES_DATA: Module[] = [
    { id: 'geo_command_center', title: 'GEO Command Center', description: 'Monitor and enhance your visibility across all Generative Engines.', icon: GeoCommandIcon, features: ['Real-time Score Tracking', 'Platform-specific Analytics', 'Content Visibility Matrix'], status: 'Active', borderColor: 'border-t-brand-primary', usageGuide: 'To use the GEO Command Center, start by entering a URL, app name, or text in the main analysis bar at the top of the screen. Once the analysis is complete, this module will show you a high-level overview of your content\'s visibility across different AI platforms (like Gemini, ChatGPT, etc.). In the \'Platform Scores\' section, you can see your score for each platform. The \'Content Visibility Matrix\' shows how specific pieces of your content perform on each AI. Use the \'Quick Actions\' to get AI-generated audits and reports.' },
    { id: 'ai_visibility_analyzer', title: 'AI Visibility Analyzer', description: 'Deep-dive analytics on your content\'s performance in AI answers.', icon: AiAnalyzerIcon, features: ['Citation Analysis', 'Competitor Benchmarking', 'Content Performance Deep-dive'], status: 'Active', borderColor: 'border-t-brand-secondary', usageGuide: 'After running an analysis from the main input bar, this module provides a deep dive. The \'Platform-Specific Analytics\' section breaks down your performance on each AI platform, including citation frequency and answer appearance rate. In \'Competitor Benchmarking\', you can see how you stack up against your competitors. \'Content Performance Deep Dive\' lists your top-performing content. You can also paste new content directly into this section to get an instant AI analysis without running a full site audit.' },
    { id: 'content_optimization_engine', title: 'Content Optimization Engine', description: 'AI-powered tools to optimize your content for maximum visibility.', icon: OptimizationIcon, features: ['AI Readiness Scoring', 'Real-time Content Editor', 'Semantic Enrichment'], status: 'Active', borderColor: 'border-t-green-500', usageGuide: 'Start by entering a URL or pasting content into the \'AI Readiness Scoring\' section to get an initial score. Then, use the \'Real-time Content Editor\' to make changes. The editor provides AI suggestions on the right. You can apply suggestions, add formatting, or refresh suggestions based on your edits. Use \'Semantic Enrichment\' to find and add related topics, and \'Platform Templates\' to automatically restructure your content for specific AIs like ChatGPT or Gemini.' },
    { id: 'technical_geo_auditor', title: 'Technical GEO Auditor', description: 'Ensure your site is technically sound for all AI crawlers.', icon: AuditorIcon, features: ['AI Crawler Compatibility', 'Structured Data Audit', 'Performance Analysis'], status: 'Active', borderColor: 'border-t-yellow-500', usageGuide: 'After running an analysis from the main input bar, this module shows your site\'s technical health. \'AI Crawler Compatibility\' shows if AI bots can access your site. \'Structured Data Optimization\' checks your schema markup and helps you generate new code. \'Performance Excellence\' analyzes your site speed, and \'Security & Trust\' checks for signals that AIs use to determine if your site is trustworthy.' },
    { id: 'competitive_intelligence', title: 'Competitive Intelligence', description: 'Track competitors and identify strategic opportunities.', icon: CIIcon, features: ['Market Share Analysis', 'Competitor Alerts', 'Opportunity Identification'], status: 'Active', borderColor: 'border-t-red-500', usageGuide: 'This module activates after you run an analysis. The \'Overview\' section gives a snapshot of your market position. The \'Market Share\' donut chart visualizes where you stand against competitors. Use the \'Strategic Alerts\' to monitor competitor actions in real-time. The \'Opportunity Identification\' section uses AI to find content gaps and strategic advantages you can exploit.' },
    { id: 'chatgpt_optimizer', title: 'ChatGPT Optimizer', description: 'Specialized tools to maximize your visibility on ChatGPT.', icon: ChatGptIcon, features: ['Q&A Readiness Scoring', 'Conversational Flow Analysis', 'GPTs Store Optimization'], status: 'Active', borderColor: 'border-t-teal-500', usageGuide: 'This module focuses specifically on ChatGPT. Use the \'Prompt-Specific Optimization\' tool by entering a target prompt and your content URL to see how well your page answers that query. \'Conversation Pattern Analysis\' shows which content formats get the most citations on ChatGPT. Use the \'Quick Actions\' to get AI-powered help with rewriting content into a Q&A format, improving definitions, and more.' },
    { id: 'perplexity_specialist', title: 'Perplexity Specialist', description: 'Optimize for fact-based search and source credibility.', icon: PerplexityIcon, features: ['Source Credibility Audit', 'Citation Format Analysis', 'Real-time Readiness Score'], status: 'Active', borderColor: 'border-t-purple-500', usageGuide: 'Perplexity values sources. Use the \'Source Credibility\' section to see how your content scores on factors like author expertise and data verification. The \'Real-time Information Readiness\' section helps you track how up-to-date your content is. Paste content into the \'Citation Format Optimization\' tool to get an AI analysis of your sourcing and suggestions for improvement.' },
    { id: 'gemini_optimizer', title: 'Gemini Optimizer', description: 'Optimize for Google AI Overviews and the Gemini ecosystem.', icon: GeminiIcon, features: ['E-E-A-T Signal Analysis', 'Multi-perspective Coverage', 'Local Intent Optimization'], status: 'Active', borderColor: 'border-t-blue-500', usageGuide: 'This module helps you optimize for Google\'s AI. The \'E-E-A-T Signal Amplification\' section analyzes your content for Experience, Expertise, Authoritativeness, and Trustworthiness. \'Multi-perspective Coverage\' helps you understand if your content covers a topic from multiple viewpoints, which Gemini prefers. Use \'Local Intent Optimization\' to see how well your content is tailored for location-based searches.' },
    { id: 'claude_compatibility', title: 'Claude Compatibility', description: 'Optimize for complex reasoning and large context windows.', icon: ClaudeIcon, features: ['Logical Flow Analysis', 'Context Window Simulation', 'Nuanced Content Generation'], status: 'Active', borderColor: 'border-t-orange-500', usageGuide: 'Claude is good with long, complex content. Paste your text into the \'Logical Flow & Coherence Analysis\' tool to score how well-structured your writing is. Use the \'Context Window Simulator\' to analyze very long documents and generate summaries that help the AI understand the context.' },
    { id: 'deepseek_specialist', title: 'DeepSeek Specialist', description: 'Optimize technical and code-heavy content.', icon: DeepSeekIcon, features: ['Code Quality Analysis', 'Technical Accuracy Scoring', 'Algorithm Clarity Check'], status: 'Active', borderColor: 'border-t-green-600', usageGuide: 'This module is for technical content. Paste a code snippet into the \'Code Quality & Efficiency Analysis\' section to get a score and suggestions from the AI. You can even ask the AI to refactor and optimize the code for you. Use the \'Quick Technical Actions\' to generate code snippets, explain algorithms, and more.' },
    { id: 'copilot_ready', title: 'Copilot Ready', description: 'Structure content for productivity and workflow integration.', icon: CopilotIcon, features: ['Actionable Guide Formatting', 'Code Snippet Optimization', 'Workflow Integration Scoring'], status: 'Active', borderColor: 'border-t-sky-500', usageGuide: 'Copilot is about productivity. First, enter a topic, URL, or code into the \'Analyze for Copilot Readiness\' text area. Then, use the \'Copilot Capabilities\' section to ask the AI to perform tasks based on that context, like generating a step-by-step guide or a code snippet. You can also connect your other workflow tools like Slack and GitHub in the \'Workflow Integration\' section.' },
    { id: 'source_intelligence', title: 'Source Intelligence', description: 'Analyze citation sources and discover new publication opportunities.', icon: SourceIntelIcon, features: ['Source Authority Tracking', 'Competitor Source Gaps', 'Publication Discovery'], status: 'Active', borderColor: 'border-t-violet-500', usageGuide: 'This module requires an analysis to be run first. It tracks where AI platforms get their information. \'Top Cited Domains\' shows which websites are cited most often. \'Competitor Source Analysis\' shows where your competitors are getting citations that you aren\'t. Use the \'Actionable Insights\' section to ask the AI for recommendations on where to publish your content to get more citations.' },
    { id: 'brand_power_scorecard', title: 'Brand Power Scorecard', description: 'Measure and track your brand\'s authority and recognition across AI platforms.', icon: BrandPowerIcon, features: ['Overall Brand Score', 'Platform-specific Authority', 'Competitive Positioning'], status: 'Active', borderColor: 'border-t-pink-500', usageGuide: 'Enter your brand name in the input field and click \'Analyze Brand\'. The AI will generate a complete scorecard that measures your brand\'s authority in the AI ecosystem. It provides an overall score, breaks it down by component (like AI Visibility and Share of Voice), and shows your rank against competitors. You can also generate a full SWOT analysis based on the results.' },
    { id: 'reporting_hub', title: 'Reporting Hub', description: 'Generate comprehensive reports on your AI visibility performance.', icon: ReportsIcon, features: ['Custom Report Builder', 'Automated Scheduling', 'White-label Reports'], status: 'Active', borderColor: 'border-t-indigo-500', usageGuide: 'Enter a URL, app name, or text into the main analysis input. Then, choose one of the report types to generate. For example, click \'Custom Report Builder\' to get a general performance report, or \'White-Label Reporting\' to get a version you can share with clients. The AI will generate a complete, formatted report in a pop-up window.' },
    { id: 'competitive_domination_dashboard', title: 'Domination Dashboard', description: 'Aggressive competitor displacement and market takeover strategies.', icon: DominationIcon, features: ['Live Leaderboard', 'Conquest Campaigns', 'Weakness Identification'], status: 'Active', borderColor: 'border-t-red-600', usageGuide: 'This is an advanced competitive analysis module. Enter your main competitor\'s brand or domain in the \'Analysis Target\' input. The dashboard shows a \'Live Leaderboard\' of where you rank against them. Use the \'Conquest Campaigns\' section to launch AI-powered strategies to outrank them. The \'Advanced Intelligence\' section helps you identify your competitor\'s weaknesses and reverse-engineer their strategy.' },
    { id: 'predictive_visibility_forecaster', title: 'Predictive Forecaster', description: 'Use AI to predict future visibility trends and market shifts.', icon: ForecasterIcon, features: ['Visibility Projections', 'Scenario Planning', 'Proactive Alerts'], status: 'Active', borderColor: 'border-t-cyan-400', usageGuide: 'Enter your brand, URL, or app name in the input field to generate a forecast. The AI will predict your future visibility score and market position. The \'Proactive Alert System\' will warn you about potential drops in visibility or new opportunities. Use the \'Scenario Planning\' section to simulate different investment strategies (e.g., Aggressive vs. Balanced) and see their predicted outcomes.' },
    { id: 'topic_conquest_engine', title: 'Topic Conquest Engine', description: 'Identify and dominate strategic content pillars in your niche.', icon: TopicConquestIcon, features: ['Content Gap Analysis', 'Topic Opportunity Scoring', 'Strategic Roadmap Generation'], status: 'Active', borderColor: 'border-t-amber-500', usageGuide: 'Enter your domain and up to 3 competitor domains. Click \'Analyze & Find Gaps\'. The AI will analyze all domains and generate a list of topic opportunities in the \'Topic Opportunity Feed\'. For each topic, you can see an opportunity score and your current content coverage. Click \'Get Brief\' to have the AI generate a full content brief for a specific topic, or click \'Generate Strategic Roadmap\' for a 3-month content plan.' },
    { id: 'global_expansion_engine', title: 'Global Expansion Engine', description: 'Optimize content for international markets and regional AI models.', icon: GlobalExpansionIcon, features: ['Cultural Adaptation', 'Regional Model Optimization', 'Automated Translation'], status: 'Active', borderColor: 'border-t-sky-400', usageGuide: 'Paste your content into the \'Content to Analyze\' text box and select a \'Target Region\'. Click \'Analyze Readiness\'. The AI will generate a report on your content\'s compatibility with regional AI models, cultural fit, and translation quality. Afterwards, you can click \'Generate Optimized Version with AI\' to have the AI automatically rewrite your content for the selected market.' },
    { id: 'api_integration_hub', title: 'API Integration Hub', description: 'Connect, distribute, and build with the AI FORCE ecosystem.', icon: ApiHubIcon, features: ['Direct API Connections', 'SDK for Custom Integrations', 'Webhook Ecosystem'], status: 'Active', borderColor: 'border-t-indigo-400', usageGuide: 'This module is for developers. In the \'Direct AI Platform Connections\' section, you can enter API keys or connect via OAuth to enable automated content distribution. The \'Automated Content Distribution\' section shows your content and allows you to publish it to your connected platforms. The \'Developer-Centric Tools\' section provides SDK examples and a place to manage webhooks for custom integrations.' },
    { id: 'industry_templates', title: 'Industry Templates', description: 'Specialized solutions for Healthcare, Legal, Finance, and more.', icon: TemplatesIcon, features: ['Sector-specific Optimizations', 'Compliance Checklists', 'Industry-tuned AI Analysis'], status: 'Active', borderColor: 'border-t-teal-400', usageGuide: 'First, paste your content into the \'Your Content\' text box at the top. Then, choose an industry template from the list below (e.g., Healthcare, Legal). Click \'Analyze & Apply Template\'. The AI will analyze your content and rewrite it to be optimized for that specific industry, focusing on relevant keywords, compliance, and audience tone.' },
    { id: 'performance_analytics', title: 'Performance & ROI', description: 'Track key performance indicators and calculate return on investment.', icon: PerformanceIcon, features: ['AI Visibility KPIs', 'ROI Calculation Engine', 'Predictive ROI Modeling'], status: 'Active', borderColor: 'border-t-emerald-400', usageGuide: 'This module helps you measure the financial impact of your AI visibility efforts. In the \'AI Visibility KPIs\' section, enter your current metrics (like citation frequency) and click \'Analyze KPIs\' to get an AI-generated analysis. In the \'ROI Calculation Engine\', input your financial data (like traffic value and lead attribution) to see a visual breakdown of your return on investment. The \'Predictive ROI Modeling\' tool lets you simulate different budget allocations to predict future ROI.' },
    { id: 'content_syndication_amplification', title: 'Content Syndication', description: 'Automate content distribution and discover partnership opportunities.', icon: SyndicationIcon, features: ['One-click Syndication', 'Partnership Discovery', 'Native Format Optimization'], status: 'Active', borderColor: 'border-t-rose-400', usageGuide: 'Connect your accounts in \'Platform Connections & Settings\' by providing API keys or URLs. Then, in the \'Syndication Hub\', you can click \'Syndicate\' on any piece of content to publish it to your connected platforms. Use the \'Partnership Discovery Engine\' to find new places to publish by entering a topic. The \'Native Format Optimization\' tool lets you paste content and have the AI rewrite it for a specific platform like ChatGPT or LinkedIn.' },
    { id: 'universal_platform_integration_hub', title: 'Universal Platform Integration Hub', description: 'Integrate e-commerce platforms like Shopify, WooCommerce, and Amazon for unified product visibility and AI-driven optimization.', icon: UniversalHubIcon, features: ['Unified E-commerce Workflow', 'Shopify, WooCommerce, Amazon Sync', 'AI Product Description Generation', 'Performance Tracking'], status: 'Active', borderColor: 'border-t-pink-400', usageGuide: 'Connect your e-commerce stores (Shopify, WooCommerce, etc.) in the \'Platform Connections\' section. Your products will be automatically imported. Use the \'Product Cockpit\' to view all your products in one place. You can select products and use the \'AI Enhancer\' to generate optimized titles, descriptions, and tags. Finally, use the \'Sync\' button to push changes back to your stores.' },
    { id: 'video_content_optimization', title: 'Video Content Optimizer', description: 'Optimize video and audio for multimodal AI search.', icon: VideoIcon, features: ['Transcript Enrichment', 'Visual Tagging', 'Voice Search Readiness'], status: 'Active', borderColor: 'border-t-fuchsia-500', usageGuide: 'Enter the URL of a video or audio file and click \'Analyze with AI\'. The AI will generate a report with several optimizations. \'Transcript Enrichment\' shows a comparison of a basic transcript versus an AI-enhanced one. \'Visual Element Tagging\' lists keywords related to the video\'s content. The module also provides scores for thumbnail attractiveness and voice search readiness.' },
    { id: 'product_schema_factory', title: 'Product Schema Factory', description: 'Generate and optimize Product schema markup for e-commerce to enhance visibility in AI-powered shopping results.', icon: ProductSchemaIcon, features: ['AI-Powered Schema Generation', 'Schema Completeness Score', 'Optimization Suggestions', 'JSON-LD Output'], status: 'Active', borderColor: 'border-t-lime-500', usageGuide: 'Enter your product details into the form. The more information you provide, the better. Click "Generate Schema with AI". The AI will create a complete JSON-LD schema for your product and provide an analysis with suggestions for improvement. You can then copy the generated schema and add it to your product page.' },
    { id: 'ai_product_description_optimizer', title: 'AI Product Description Optimizer', description: 'Craft compelling, high-converting product descriptions optimized for major e-commerce platforms like Amazon, Shopify, and Etsy.', icon: ProductDescriptionIcon, features: ['Platform-Specific Tone', 'SEO Keyword Integration', 'Feature-to-Benefit Conversion', 'A/B Test Variations'], status: 'Active', borderColor: 'border-t-emerald-500', usageGuide: 'Enter your product name, key features, and target audience. Select the e-commerce platforms you are targeting. The AI will generate multiple description variants, each tailored to the specific platform\'s audience and algorithm.' },
];